/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author F.Nurhayati
 */
public class Menu extends javax.swing.JFrame {
    // membuat objek baru dari class Login yang sudah terkoneksi dengan database
    Login bb = new Login();

    /**
     * Creates new form Menu
     */
   public Menu() {
    // mengecek sudah login atau belum
    // jika belum login akan di redirect ke form login
    if ("AKTIF".equals(Session.getStatusLogin())) { 
        initComponents();
        setSessionNama();
    } else {
        // menutup menu tanpa keluar dari aplikasi
        dispose();
        // memanggil form login
        LoginForm form = new LoginForm();
        form.setVisible(true);
    }
}

private void setSessionNama() {
    // Periksa apakah nama tidak null sebelum menampilkan
    if (Session.getNama() != null) {
        label_nama.setText("Hai " + Session.getNama());
    } else {
        label_nama.setText("Hai Guest");
    }
    label_keterangan.setText("Selamat datang di aplikasi praktikum PBO");
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_nama = new javax.swing.JLabel();
        label_keterangan = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAplikasiBar = new javax.swing.JMenu();
        jMenuKeluar = new javax.swing.JMenuItem();
        jMenucrud = new javax.swing.JMenu();
        jMenuCRUD = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_nama.setText("haii");

        label_keterangan.setText("Loading..");

        jMenuAplikasiBar.setText("Aplikasi");

        jMenuKeluar.setText("Keluar");
        jMenuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuKeluarActionPerformed(evt);
            }
        });
        jMenuAplikasiBar.add(jMenuKeluar);

        jMenuBar1.add(jMenuAplikasiBar);

        jMenucrud.setText("CRUD");

        jMenuCRUD.setText("CRUD Siswa");
        jMenuCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCRUDActionPerformed(evt);
            }
        });
        jMenucrud.add(jMenuCRUD);

        jMenuBar1.add(jMenucrud);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 202, Short.MAX_VALUE))
                    .addComponent(label_keterangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(label_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuKeluarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan keluar?", "Warning", JOptionPane.YES_NO_OPTION)
        == JOptionPane.YES_OPTION) {
    try {
        bb.logout(Session.getUserID());
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal logout: " + e.getMessage());
    }
    System.exit(0);
}

    }//GEN-LAST:event_jMenuKeluarActionPerformed

    private void jMenuCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCRUDActionPerformed
         try{
        // memanggil form siswa
        Form_Siswa form = new Form_Siswa();
        form.setVisible(true);
    }catch(Exception ex){
 }
    }//GEN-LAST:event_jMenuCRUDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAplikasiBar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCRUD;
    private javax.swing.JMenuItem jMenuKeluar;
    private javax.swing.JMenu jMenucrud;
    private javax.swing.JLabel label_keterangan;
    private javax.swing.JLabel label_nama;
    // End of variables declaration//GEN-END:variables
}
